KinsonDigital/CASL

- .github/ISSUE_TEMPLATE/bug-report.md
Create a bug report issue template to assist in creating bugs
> Create bug report issue template

- .github/workflows/main.yml
- .github/workflows/pre-release.yml
- .vscode/settings.json
- CASL/CASL.csproj
This PR is for pre-release **v1.0.0-preview.1**
---
1. [x] Verify that the entire solution builds locally using **Visual Studio**
2. [x] Verify that all unit tests pass locally using **Visual Studio**
3. [x] Check the code to make sure that it follows the coding standards
* This can be done by checking for and processing any warnings in **Visual Studio** that are generated by the solution analyzers.
* NOTE: Not following the coding standards will most likely result in a PR being declined  There are times when it makes sense to not follow a particular rule or standard.  If this is the case, bring up the issue to one of the maintainers and we can definitely review it!! 🙂
4. [x] Verify that the code changes have been reviewed and checked off for the PR
5. [x] Verify that related issue …
> Start of v1.0.0-preview.1

- .github/workflows/pre-release.yml
- CASL/CASL.csproj
This PR removes the `IContent` interface.
---
1. [x] Verify that the entire solution builds locally using **Visual Studio**
2. [x] Verify that all unit tests pass locally using **Visual Studio**
3. [x] Check the code to make sure that it follows the coding standards
* This can be done by checking for and processing any warnings in **Visual Studio** that are generated by the solution analyzers.
* NOTE: Not following the coding standards will most likely result in a PR being declined  There are times when it makes sense to not follow a particular rule or standard.  If this is the case, bring up the issue to one of the maintainers and we can definitely review it!! 🙂
4. [x] Verify that the code changes have been reviewed and checked off for the PR
5. [x] Verify that related issue numbers are …
> Remove the IContent interface

- .github/workflows/prev-release.yml
- .github/workflows/prod-release.yml
- .github/workflows/qa-release.yml
- BuildScripts/PackageTestingApp.ps1
- BuildScripts/ScriptStart.ps1
- CASL/CASL.csproj
This pull request performs a preview release for version **_v1.0.0-preview.9_**
---
---
* **Example:** 🚀Release To Preview - v1.2.3.preview.4
- 💡 A version-release branch is the branch used for preview releases and has a syntax of **_release/v1.2.3_**
- 💡 A non-version-release is a branch prefixed with **_release/_** and does NOT have a version after the **_release/_** section.  Non version release branches bring changes to a prerelease.
- 💡 Status checks are put in place to run unit tests every single time a change is pushed to a PR.  This does not mean that the tests pass in both the local and CI environment.
- 💡 Every change to a PR will run a status check to confirm that the version has the correct syntax and does not already exist in the repository.
- 💡 Make sure to add the …
> Release To Preview - v1.0.0.preview.9

- .github/PULL_REQUEST_TEMPLATE/feature-to-develop.md
- .github/PULL_REQUEST_TEMPLATE/preview-release-to-release.md
- .github/PULL_REQUEST_TEMPLATE/release-to-master.md
- .github/workflows/prev-build-status-check.yml
- .github/workflows/prev-release-version-status-check.yml
- .github/workflows/prev-release.yml
- .github/workflows/prev-unit-testing-status-check.yml
- .github/workflows/prod-release-version-status-check.yml
- .github/workflows/prod-release.yml
- .github/workflows/tag-does-not-exist-status-check.yml
- CASL/CASL.csproj
This pull request performs a preview release for version **_v1.0.0-preview.10_**
---
---
* **Example:** 🚀Release To Preview - v1.2.3.preview.4
- 💡 A **_preview release branch_** is used for preview releases and has a syntax like **_preview/v1.2.3-preview.4_**
- 💡 A release branch has the syntax like **_release/v1.2.3_**.
- 💡 Status checks are put in place to run unit tests every single time a change is pushed to a PR.  This does not mean that the tests pass in both the local and CI environment.
- 💡 Every change to a PR will run a status check to confirm that the version has the correct syntax and does not already exist in the repository.
- 💡 Make sure to add the **_.preview.\<number\>_** syntax to the end of the version
- **Example:**
``` html
<Version>1.2.3.preview.4</Version> …
```
> 🚀Release To Preview - v1.0.0-preview.10

- .github/workflows/build-status-check.yml
- .github/workflows/feature-pr-branches-status-check.yml
- .github/workflows/qa-prod-releases.yml
- .github/workflows/tag-does-not-exist-status-check.yml
- .github/workflows/unit-testing-status-check.yml
- .github/workflows/validate-preview-release-branches-status-check.yml
- .github/workflows/validate-prod-release-branches-status-check.yml
- .github/workflows/version-status-check.yml
- .gitignore
Reverts KinsonDigital/CASL#72
This is to add a forgotten commit
> Revert "Start of workflow and doc updates"

- BACKERS.md
This pull request is for creating a backers file in the root of the repository
> Create a backers markdown file

- .github/workflows/triage-issue.yml
> Add workflow to auto label new issues

- .github/ISSUE_TEMPLATE/release-todo-issue-template.yml
<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> Fix release todo issue template 

- CASL/CASL.csproj
- Testing/CASLTesting/CASLTesting.csproj
- Testing/CASLTests/CASLTests.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Update to the latest version of dotnet

- CASL/CASL.csproj
- Testing/CASLTesting/CASLTesting.csproj
- Testing/CASLTests/CASLTests.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Update System.IO.Abstractions library

- Documentation/Images/twitter-logo-16x16.svg
- README.md
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Update maintainer Twitter link on home page

- CASL.sln
- CONTRIBUTING.MD
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Add contributing doc

- README.md
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Add badges to README

- .github/workflows/prev-feature-pr-status-check.yml
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Fix workflow issues

- LICENSE.md
- README.md
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Update Readme

- renovate.json
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Create renovate config

- CASL/CASL.csproj
- Testing/CASLTesting/CASLTesting.csproj
- Testing/CASLTests/CASLTests.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
> 🚧Update all nuget packages

- .github/workflows/sync-bot-status-check.yml
- .github/workflows/sync-issue-to-pr.yml
- CASL.sln
- CASL/Sound.cs
To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #144
✅ The pull request head branch must be a feature branch with the syntax `feature/<issue-num>-sync-testing`. 
✅ The pull request base branch must be a 'master' or 'preview' branch. 
✅ The pull request head branch contains a valid issue number. 
✅ The pull request title matches the linked issue title exactly. 
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request. 
✅ The pull request assignees match the assignees of the issue. 
✅ The pull request labels match the labels of the issue. 
✅ The pull request organizational projects match the organizational projects of the issue. 
✅ The pull requests milestone …
> ✨ Stop marking Sound as sealed

- README.md
To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #228
✅ The pull request head branch must be a feature branch with the syntax `feature/<issue-num>-sync-testing`. 
✅ The pull request base branch must be a 'master' or 'preview' branch. 
✅ The pull request head branch contains a valid issue number. 
✅ The pull request title matches the linked issue title exactly. 
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request. 
✅ The pull request assignees match the assignees of the issue. 
✅ The pull request labels match the labels of the issue. 
✅ The pull request organizational projects match the organizational projects of the issue. 
✅ The pull requests milestone …
> 🚧Fix badges in readme
